name: "internally receive PR"

# Controls when the workflow will run
on:
  pull_request_target:
    branches: [ "main" ]
jobs:
  test-pr:
    name: "Test if pull request is valid"
    if: ${{ github.event.action != 'closed' }}
    runs-on: ubuntu-latest
    outputs:
      is_valid: ${{ steps.check-pr.outputs.VALID }}
      MSG: ${{ steps.check-pr.outputs.MSG }}
    steps:
      - name: "Check PR"
        id: check-pr
        run: |
          echo "::set-output name=VALID::true"
          echo "::set-output name=MSG::all good :)"

      - name: "Comment on PR"
        id: comment-diff
        if: ${{ always() && steps.check-pr.outputs.VALID != true && steps.check-pr.outputs.MSG != '' }}
        uses: carpentries/actions/comment-diff@main
        with:
          pr: ${{ github.event.number }} 
          body: |

            EVERYTHING IS FINE. Approve the workflow!
            Trust meeeee
